target("dosemu-freedos")
    set_kind("phony")
    on_install(function (target)
        local installdir = target:installdir()
        local bindir = path.join(installdir, "bin")
        local sharedir = path.join(installdir, "share")
        local commandsdir = path.join(sharedir, "dosemu/commands")
        local dosrcddir = path.join(commandsdir, "dosemu/dosrc.d")
        local libexecdir = path.join(installdir, "libexec", "dosemu")
        os.mkdir(libexecdir)
        os.cp("$(projectdir)/src/dosemu-downloaddos", bindir)
        os.ln(path.join(bindir, "dosemu-downloaddos"), path.join(libexecdir, "dosemu-downloaddos"))
        os.cp("$(projectdir)/src/dosemu-installfreedosuserspace", bindir)
        os.ln(path.join(bindir, "dosemu-installfreedosuserspace"), path.join(libexecdir, "dosemu-installfreedosuserspace"))
        os.cp("$(projectdir)/src/dosemu-installfreedos",  bindir)
        os.cp("$(projectdir)/src/bat/insfdusr.bat", path.join(commandsdir, "bat"))
        os.mkdir(dosrcddir)
        os.cp("$(projectdir)/src/bat/dosrc.d/bin2path.bat", dosrcddir)
        os.cp("$(projectdir)/src/bat/dosrc.d/sugfdusr.bat", dosrcddir)
    end)
    on_uninstall(function (target)
        local installdir = target:installdir()
        local bindir = path.join(installdir, "bin")
        local sharedir = path.join(installdir, "share")
        local commandsdir = path.join(sharedir, "dosemu/commands")
        local dosrcddir = path.join(commandsdir, "dosemu/dosrc.d")
        local libexecparentdir = path.join(installdir, "libexec")
        local libexecdir = path.join(installdir, "libexec", "dosemu")
        os.rm(path.join(bindir, "dosemu-downloaddos"))
        os.rm(path.join(libexecdir, "dosemu-downloaddos"))
        os.rm(path.join(bindir, "dosemu-installfreedosuserspace"))
        os.rm(path.join(libexecdir, "dosemu-installfreedosuserspace"))
        os.rm(path.join(bindir, "dosemu-installfreedos"))
        os.rm(path.join(sharedir, "dosemu/commands/bat/insfdusr.bat"))
        os.rm(path.join(sharedir, "dosemu/commands/dosemu/dosrc.d/bin2path.bat"))
        os.rm(path.join(sharedir, "dosemu/commands/dosemu/dosrc.d/sugfdusr.bat"))
        if os.emptydir(libexecdir) then os.rmdir(libexecdir) end
        if os.emptydir(libexecparentdir) then os.rmdir(libexecparentdir) end
        if os.emptydir(dosrcddir) then os.rmdir(dosrcddir) end
    end)
