#!/usr/bin/python3

import os
import shutil
import subprocess
import sys

CACHE_DIR = os.path.join(os.environ['HOME'], '.cache', 'dosemu')
FREEDOS_VERSION = '12'
DOS_NAME = 'freedos' + FREEDOS_VERSION
DESTINATION = os.path.join(os.environ['HOME'], '.dosemu', 'install', DOS_NAME, 'drive_c')

SCRIPT_ROOT = os.path.dirname(os.path.realpath(__file__))

download_dir = os.path.join(CACHE_DIR, DOS_NAME)
if (subprocess.run([os.path.join(SCRIPT_ROOT, 'dosemu-downloaddos'), '-o', DOS_NAME, '-d', download_dir]).returncode == 0):
    subprocess.run([os.path.join(SCRIPT_ROOT, 'dosemu-setupfreedos'), '-s', download_dir, '-d', DESTINATION, '-v', 'full'])

print('A full installation of FreeDOS 1.2 was done.')
print('To use: dosemu -dos ' + DOS_NAME)
print('The root drive can be found at: ' + DESTINATION)
