#!/usr/bin/python3

import os
import shutil
import subprocess
import sys

CACHE_DIR = os.path.join(os.environ['HOME'], '.cache', 'dosemu')
FREEDOS_VERSION = '13'

SCRIPT_ROOT = os.path.dirname(os.path.realpath(__file__))

download_dir = os.path.join(CACHE_DIR, 'freedos' + FREEDOS_VERSION)
rc = subprocess.run([os.path.join(SCRIPT_ROOT, 'dosemu-downloaddos'), '-o', 'freedos' + FREEDOS_VERSION + 'userspace', '-d', download_dir]).returncode
if (rc == 0):
    rc = subprocess.run([os.path.join(SCRIPT_ROOT, 'dosemu-setupfreedos'), '-s', download_dir, '-d', os.path.join(os.environ['HOME'], '.dosemu', 'drive_c'), '-v', 'userspace']).returncode
sys.exit(rc)
